### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by liuyq123** [dohlee/chromoformer#2]
Hello, I got some errors when trying to retrain Chromoformer. I first downloaded and processed data with the pipeline provided in the `preprocessing` folder, and then ran `train.py` in the `chromoformer` folder. However, I got FileNotFoundError. Any ideas on how to fix it? Thanks.

**Comment by dohlee** [comment]
Sure. Could you please paste the full error message here? It would greatly help to diagnose the issue. 

Thanks.

**Comment by liuyq123** [comment]
Thank you so much! Here's the error message.
<img width="1133" alt="Screen Shot 2022-06-28 at 12 39 14 AM" src="https://user-images.githubusercontent.com/47292066/176094196-f555c79a-d877-4aa2-b49f-aedadeb161eb.png">

**Comment by dohlee** [comment]
Thank you for your report. The problem was that `preprocessing/scripts/extract_signals.py` was generating wrong read depth signals for regions around TSS. I fixed `preprocessing/scripts/extract_signals.py` to resolve it. 

Could you please remove the `data` directory under `preprocessing` directory, pull the current version of github repo (where `extract_signals.py` is fixed) and re-run the snakemake pipeline to generate correct `.npy` files? If the model training works fine with that, then I'll close this issue. 

Thank you again for opening this issue, and please let me know whether it works or not.

**Comment by liuyq123** [comment]
Thanks a lot for fixing the problem! It works well now.

**Comment by dohlee** [comment]
Good. Closing the issue.
